name: 'Setup Qualification Environment'
description: 'Install OSPSuite tools and Qualification Framework based on csv file input'
author: 'pchelle'

inputs:
  tools-path: 
    description: 'Path a csv file defining the tools and versions to install'
    required: true
outputs:
  tools-table:
    description: "Markdown table corresponding to csv tools information"
    value: ${{ steps.tools_data.outputs.json  }}
  
runs:
  using: "composite"
  steps:
    - id: install-r
      name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1'
        use-public-rspm: true
    
    - id: copy-tools
      name: Copy tools.csv
      run: |
        cp -n ${{ inputs.tools-path }} tools.csv
      shell: bash
      
    - id: read-tools
      name: Read and export tools.csv
      run: |
        Rscript r-scripts/install_tools.R
      shell: bash

    - id: save-tools-json
      name: Save tools.json
      run: |
        Rscript -e 'install.packages("jsonlite", repos="https://cloud.r-project.org/")'
        Rscript -e 'cat(jsonlite::toJSON(read.csv("tools.csv", stringsAsFactors = FALSE, colClasses = "character"), dataframe = "rows"), file = "tools.json")'
      shell: bash

    - id: tools_data
      name: Output tools data for table conversion      
      run: |
        echo "json=$(cat tools.json)" >> $GITHUB_OUTPUT
      shell: bash
