name: Cache Qualification Environment

on:
  workflow_dispatch:
    inputs:
      tools-path:
        type: string
        description: 'Path of csv file defining tools to install'
        required: true
        default: 'tools.csv'

permissions: write-all

jobs:
  print-tools-table:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: qualification-environment
        name: Setup Qualification Environment
        uses: pchelle/osp-actions/setup-qualification-environment@main
        with:
          tools-path: ${{ inputs.tools-path }}

      - id: files
        name: Check available files
        run: |
          ls
          ls '${{ runner.tool_cache }}'
          ls '${{ github.workspace }}'
          ls 'C:/'
        shell: bash
      
      - id: cache
        name: Cache Qualification Environement
        # TODO: save R, npm and pandoc installations
        uses: actions/cache/save@v4
        with:
          path: |
            QualificationRunner
            PK-Sim
            ${{ github.workspace }}/node_modules
            C:/Program Files/Pandoc
            ${{ runner.tool_cache }}/R
            C:/Users/${{ env.USERNAME }}/Documents/R
          key: ${{ hashFiles(inputs.tools-path) }}
