name: Cache Qualification Environment

on:
  workflow_dispatch:
    inputs:
      tools-path:
        type: string
        description: 'Path of csv file defining tools to install'
        required: true
        default: 'tools.csv'

permissions: write-all

jobs:
  print-tools-table:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: qualification-environment
        name: Setup Qualification Environment
        uses: pchelle/osp-actions/setup-qualification-environment@main
        with:
          tools-path: ${{ inputs.tools-path }}

      - id: files
        name: Check github paths
        run: |
          echo 'Runner tool cache: ${{ runner.tool_cache }}'
          echo 'Github workspace: ${{ github.workspace }}'
          echo 'Runner temp: ${{ runner.temp }}'
        shell: bash

      - id: tool-cache
        name: Check tool cache
        run: |
          ls '${{ runner.tool_cache }}'
        shell: bash
      
      - id: cache
        name: Cache Qualification Environement
        uses: actions/cache/save@v4
        with:
          path: |
            QualificationRunner
            PK-Sim
            ${{ github.workspace }}/node_modules
            ${{ runner.tool_cache }}
            ${{ runner.temp}}/Library
          key: ${{ hashFiles(inputs.tools-path) }}
          # C:/Users/${{ env.USERNAME }}/Documents/R
