name: Test Qualification Environment Setup

on:
  workflow_dispatch:
    inputs:
      from-cache:
        type: boolean
        description: Use cached setup if available
  
permissions: write-all

jobs:
  print-tools-table:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - id: qualification-environment
        name: Setup Qualification Environment
        uses: pchelle/osp-actions/setup-qualification-environment@main
        with:
          tools-path: tools.csv
          from-cache: ${{ github.event.inputs.from-cache }}

      - id: print-output
        # Leverage installed environment
        name: Print output from previous step
        run: |
          print(ospsuite.reportingengine::getReportingEngineInfo())
          print("Qualification Framework Version")
          print("${{ steps.qualification-environment.outputs.qualification-framework-version }}")
          print("PK-Sim Version")
          print("${{ steps.qualification-environment.outputs.pk-sim-version }}")
        shell: Rscript {0}

      - id: print-table
        name: Print output table from previous step
        run: |
          echo ${{ steps.tools-versions.outputs.tools-table  }}
        shell: bash
        
