name: Test Qualification Environment Setup

on:
  workflow_dispatch:
    inputs:
      from-cache:
        type: boolean
        description: Use cached setup if available
  
permissions: write-all

jobs:
  print-tools-table:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: tools-versions
        name: Get tools versions
        uses: pchelle/osp-actions/get-tools-versions@main
        with:
          tools-path: tools.csv
      
      - id: install-from-cache
        if: ${{ inputs.from-cache }} == 'true'
        name: Set up environment from cache
        uses: actions/cache/restore@v4
        with:
          path: |
            QualificationRunner
            PK-Sim
            **/npm
            **/Pandoc
            **/Program Files/R
          key: cache-${{ hashFiles('tools.csv') }}
          # inputs.tools-path
        
      - id: qualification-environment
        if: ${{ inputs.from-cache }} != 'true'
        name: Setup Qualification Environment
        uses: pchelle/osp-actions/setup-qualification-environment@main
        with:
          tools-path: tools.csv

      - id: print-output
        # Leverage installed environment
        name: Print output from previous step
        run: |
          print(ospsuite.reportingengine::getReportingEngineInfo())
          print("Qualification Framework Version")
          print("${{ steps.tools-versions.outputs.qualification-framework }}")
          print("PK-Sim Version")
          print("${{ steps.tools-versions.outputs.pk-sim }}")
        shell: Rscript {0}

      - id: print-table
        name: Print output table from previous step
        run: |
          echo ${{ steps.tools-versions.outputs.tools-table  }}
        shell: bash
        
