name: Test Qualification Environment Setup

on:
  workflow_dispatch:
    inputs:
      from-cache:
        required: true
        type: boolean
        description: Use cached setup if available
  
permissions: write-all

jobs:
  print-tools-table:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: tools-versions
        name: Get tools versions
        uses: pchelle/Workflows/.github/actions/get-tools-versions@118_tools
        with:
          tools-path: tools.csv

      - id: check-tools-versions
        name: Check tools defined in tools.csv
        run: |
          echo 'PK-Sim version: ${{ steps.tools-versions.outputs.pk-sim  }}'
          echo 'Qualification framework version: ${{ steps.tools-versions.outputs.qualification-framework  }}'
          echo 'OSPSuite-R version: ${{ steps.tools-versions.outputs.ospsuite-r  }}'
          echo 'Reporting Engine version: ${{ steps.tools-versions.outputs.reporting-engine  }}'
          echo 'TLF version: ${{ steps.tools-versions.outputs.tlf  }}'
          echo 'R version: ${{ steps.tools-versions.outputs.r  }}'
        shell: bash

      - id: tools-table
        name: Print markdown table of tools
        run: |
          echo '${{ steps.tools-versions.outputs.tools-table  }}'
        shell: bash
      
      - id: qualification-environment
        name: Setup Qualification Environment
        uses: pchelle/Workflows/.github/actions/setup-qualification-environment@118_tools
        with:
          tools-path: tools.csv

      - id: test-environment-is-installed
        name: Test environment is installed
        run: |
          print(ospsuite.reportingengine::getReportingEngineInfo())
        shell: Rscript {0}
